
name: Python application

on:
  schedule:
   - cron: '10,15,20,25,30,35,40,45,50,55,00,05 * * * *' 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo /etc/init.d/mysql start
    - name: Run main
      env:
        DATABASE: ${{ secrets.DATABASE }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_SERVICE_ID: ${{ secrets.DATABASE_SERVICE_ID }}
        DATABASE_SERVICE_TOKEN: ${{ secrets.DATABASE_SERVICE_TOKEN }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        MYSQL_ATTR_SSL_CA: ${{ secrets.MYSQL_ATTR_SSL_CA }}
        PORT: ${{ secrets.PORT }}
      run: |
        python3 just_db_refresh.py
