
name: Python application

on:
  schedule:
   - cron: '57 * * * *' 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run main
      env:
        ${{ secrets.DATABASE }}
        ${{ secrets.DATABASE_HOST }}
        ${{ secrets.DATABASE_PASSWORD }}
        ${{ secrets.DATABASE_SERVICE_ID }}
        ${{ secrets.DATABASE_SERVICE_TOKEN }}
        ${{ secrets.DATABASE_USERNAME }}
        ${{ secrets.MYSQL_ATTR_SSL_CA }}
        ${{ secrets.PORT }}
      run: |
        python3 just_db_refresh.py
